### ISSUE TITLE
Missing ability  to specify values for helm charts in extensions

### ISSUE THREAD

**Issue by vangourd** [johbo/k0s-nix#10]
Looking at the extensions file I feel like there's a mkOption missing for values to be added here?

https://github.com/johbo/k0s-nix/blob/main/nixos/extensions.nix

K0S supports specifying chart values in the config so maybe there's another way to specify this.

Can anyone advise if this is true?

**Comment by vangourd** [comment]
I've created a PR to add this option which allows passing a string of YAML into the k0s config which is then passed to the chart. 

https://github.com/johbo/k0s-nix/pull/11

**Comment by plaflamme** [comment]
Fixed as part of https://github.com/johbo/k0s-nix/pull/11
